debug: true # 框架中通过 cfgSvc.IsDebug() 获取

goodlog:
  level: trace

runtime:
  path: ./runtime_dir

swagger:
  filepath: docs/swagger.json
  host: localhost
  port: 4545

etcd:
  # etcd 服务器配置
  server:
    # etcd 服务器节点列表
    endpoints:
      - http://localhost:2379
    dial_timeout_secods: 5 # 连接 etcd 服务器的超时时间

  # 服务注册配置，用于将本服务注册到 etcd
  client:
    service_name: my-services # 服务名称标识
    service_addr: "192.168.1.200:2003" # 本服务的监听地址